/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#003d9b',
        'primary-container': '#0052cc',
        'on-primary': '#ffffff',
        'on-primary-container': '#c4d2ff',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
        secondary: '#525f73',
        'secondary-container': '#d6e3fb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#586579',
        'secondary-fixed': '#d6e3fb',
        'secondary-fixed-dim': '#bac7de',
        'on-secondary-fixed': '#0f1c2d',
        'on-secondary-fixed-variant': '#3b485a',
        tertiary: '#6c3500',
        'tertiary-container': '#8f4800',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffc8a4',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7f9fc',
        surface: '#f7f9fc',
        'surface-bright': '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'on-surface': '#191c1e',
        'on-background': '#191c1e',
        'on-surface-variant': '#434654',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#0c56d0',
        'outline': '#737685',
        'outline-variant': '#c3c6d6',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f4',
        'inverse-primary': '#b2c5ff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
      },
    },
  },
  plugins: [],
}
